### PR TITLE
Added function reqMatchingSymbols that searches all available symbols…

### PR DESCRIPTION
**Pull request by Wesseldr**
Implemented the reqMatchingSymbols call. It returns a dataframe with the matched symbols. The search matches tickers and names. IB will only return a maximum of 16 matches.
see https://interactivebrokers.github.io/tws-api/matching_symbols.html
If no symbols are found, it returns an empty dataframe.

### CODE REVIEW

**Comment by joshuaulrich** [comment]
@Wesseldr Thanks again for this contribution! I just noticed that you used `glue::trim()`. IBrokers doesn't use glue and I don't want to add a dependency for one line of code. Can you tell me why we need `glue::trim()` here?

It would be nice if you could provide the output of `dput(derivativeSecTypes)` before and after the call to `glue::trim()`. That will help me understand why it's needed and find a solution using available packages.

**Comment by Wesseldr** [comment]
it trims away the white spaces. but perhaps native R works there as well..

Wessel
"No matter where you go, there you are" from Buckaroo Banzai

**Comment by joshuaulrich** [comment]
There's `base::trimws()` to strip leading/trailing whitespace. I'm not sure what `glue::trim()` does. The documentation is not helpful at all.

> This trims a character vector according to the trimming rules used by glue.

But doesn't say or reference what those trimming rules are. And the 'Examples' section does not give examples of the `trim()` function.

**Comment by Wesseldr** [comment]
Ws more of a courtesy to the client that it doesn't get the mess that IB
sends over with CSV strings that end on a , etc... at least I think its
taht part of the code.
But will do fine without it I think, the user has to deal with additional
spaces at the beginning of a string and the end of a string..

"No matter where you go, there you are" from Buckaroo Banzai

**Comment by Wesseldr** [comment]
(but I get that you try to minimize the dependence as much as possible :-)
"No matter where you go, there you are" from Buckaroo Banzai

**Pull request merged**
