### PR TITLE
SW-May2015 - updating IBrokers to IB clientVersion63

### PR DESCRIPTION
**Pull request by censix**
Hi Joshua

I worked on incorporating my changes into the IBrokers package source code.  The package builds ok with "R CMD build ...", but I have no time to do extensive (unit) testing at the moment. Please review the changes and modify as you see fit.

regards

Soren

### CODE REVIEW

**Comment by joshuaulrich** [comment]
Thanks for the patch, but it's very hard to review the functional changes with all the changes to formatting, comments, and whitespace.

Even [ignoring whitespace changes](https://github.com/joshuaulrich/IBrokers/pull/9/files?w=1), there are still a lot of comments removed, wrapped lines added, braces on same/new lines, etc.  It will take me a long time to carefully review all the changes to look for the meaningful changes you made.

**Comment by censix** [comment]
Jashua, it is your decision if you want to incorporate these changes into
the official IBrokers package of course.  I am just making them available
to you as the package maintainer.  Unfortunately I do not have the time to
give each function the 'look and feel'  you would like to see. That is
cosmetics .... unless you or others would like to sponsor that time.  Best
regards.

**Comment by joshuaulrich** [comment]
My comment has nothing to do with cosmetics.  My point is that I cannot review your changes without spending a substantial amount of my time manually searching for the changes you made that would actually affect functionality.

**Comment by kalka0** [comment]
Hello Joshua. I am an happy user of IBrokers. A very valuable tool. Unfortunately the package has become unreliable since the IB changes mentioned in this post. twsConnect assigns random clientIds, and often $clientId provides a wrong code (i.e. the clientId assigned by IB is different from what is seems). I would love to contribute somehow to fix this but unfortunately IBrokers is well beyond my skills. I am wondering if you plan some fix anytime soon... Thanks

**Comment by mariope** [comment]
#14

**Comment by vspinu** [comment]
Heads up about [rib](https://github.com/vspinu/rib) which is a wrapper around official tws-api client. Thus aims to be 100% feature complete and easy to maintain.

**Pull request closed without merging**
